# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-12 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190205_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('attended1', models.CharField(max_length=5)),
                ('attended2', models.CharField(max_length=5)),
                ('attended3', models.CharField(max_length=5)),
                ('attended4', models.CharField(max_length=5)),
                ('attended5', models.CharField(max_length=5)),
                ('attended6', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='FOOD.png', upload_to='profile_pics'),
        ),
    ]
