# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-15 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_videos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userscore',
            old_name='score',
            new_name='score1',
        ),
        migrations.AddField(
            model_name='userscore',
            name='attended10',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='userscore',
            name='attended11',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='userscore',
            name='attended12',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='userscore',
            name='attended13',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='userscore',
            name='attended14',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='userscore',
            name='attended15',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='userscore',
            name='attended7',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='userscore',
            name='attended8',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='userscore',
            name='attended9',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userscore',
            name='score9',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='attended1',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='attended2',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='attended3',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='attended4',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='attended5',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='attended6',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
