# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-21 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190315_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='totalScore',
            field=models.IntegerField(default=0),
        ),
    ]
