# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-29 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190329_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='invalid.jpg', upload_to='profile_pics'),
        ),
    ]
